name: Build

on:
  pull_request:
    branches:
      - jda
  push:
    branches:
      - jda

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[CI-SKIP]')"
    name: Compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Compile
        run: mvn clean package