name: Build Pull Request


on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.idea/copyright/*.xml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 21

      - name: Build GeyserBot
        run: ./gradlew build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: GeyserBot
          path: build/libs/GeyserBot.jar
